#lang scheme

(define (deriv exp var)
  (cond ((number? exp) 0)
        ((variable? exp)
         (if (same-variable? exp var) 1 0))
        ((sum? exp)
         (make-sum (deriv (addend exp) var)
                   (deriv (augend exp) var)))
        ((product? exp)
         (make-sum
          (make-product (multiplier exp)
                        (deriv (multiplicand exp) var))
          (make-product (deriv (multiplier exp) var)
                        (multiplicand exp))))
        (else
         (error "unkown expression type -- DERIV" exp))))

(define variable? symbol?)
(define (same-variable? v1 v2)
  (and (variable? v1) (variable? v2) (eq? v1 v2)))
(define (make-sum a1 a2)
  (cond ((eq? a1 0) a2)
        ((eq? a2 0) a1)
        ((and (number? a1) (number? a2)) (+ a1 a2))
        (else (list a1 '+ a2))))
(define (make-product m1 m2)
  (cond ((or (eq? m1 0) (eq? m2 0)) 0)
        ((eq? m1 1) m2)
        ((eq? m2 1) m1)
        ((and (number? m1) (number? m2)) (* m1 m2))
        (else (list m1 '* m2))))

(define (sum? x)
  (cond ((not (and (pair? x) (pair? (cddr x)))) #f)
        ((eq? (cadr x) '+) #t)
        ((empty? (cdddr x)) #f)
        (else (sum? (cddr x)))))

(define (addend s)
  (define (helper accu rest)
    (if (eq? (car rest) '+)
        (if (empty? (cdr accu)) (car accu) accu)
        (helper (append accu (list (car rest)))
                (cdr rest))))
  (helper '() s))

(define (augend s)
    (if (eq? (car s) '+)
        (if (empty? (cddr s)) (cadr s) (cdr s))
        (augend (cdr s))))

(define (product? x)
  (and (and (and (pair? x) (pair? (cddr x))) (eq? (cadr x) '*)) (not (sum? x))))
(define (multiplier p) (car p))
(define (multiplicand p)
  (if (empty? (cdddr p))
      (caddr p)
      (if (not (sum? (cddr p)))
          (cddr p)
          (error "Not a product!"))))

